---
title: "PSTAT 174 Final Project"
author: "Navin Lo"
date: "2024-06-07"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=F}
library(astsa)
library(tseries)
library(forecast)
library(dplyr)
library(tidyverse)
library(MASS)
library(fGarch)
library(rugarch)
library(pander)

NKE = read.csv("NKE.csv")
head(NKE, 10)
```

```{r}
NKE$Date = as.Date(NKE$Date, format="%Y-%m-%d")

closing = NKE$Close
NKE_ts = ts(closing)

x_labels = c("6/2023", "9/2023", "12/2023", "3/2024", "6/2024")
label_positions = seq(1, length(NKE_ts), length.out=length(x_labels))
label_positions = round(label_positions)
par(mar = c(5, 5, 5, 2), las = 1)
plot.ts(NKE_ts, main="Time Series of Nike Closing Stock Price \n Jun. 2023 - Jun. 2024",
     ylab="Closing Price", xlab="Date", xaxt="n")
axis(1, at=label_positions, labels=x_labels)
```

```{r}
adf.test(NKE_ts)
acf2(NKE_ts, main='ACF and PACF of NKE Closing Prices', 25)
```


```{r}
NKE_log_diff = diff(log(NKE_ts))
adf.test(NKE_log_diff)
plot.ts(NKE_log_diff, main='First Difference of Log Closing Stock Prices',
        ylab="Log Difference")
acf2(NKE_log_diff, main = 'ACF and PACF of First Difference Log Prices', 25)
```

# SARIMA

```{r}
auto.arima(NKE_ts)
NKE_sarima = sarima(NKE_ts, 2, 1, 0)
```

```{r}
fcast_sarima = sarima.for(NKE_ts, n.ahead=252, p=2, d=1, q=0, plot.all=TRUE,
                          main="ARIMA (2, 1, 0) Forecast")
```

```{r}
arma = arima(NKE_log_diff, order=c(2,1,0))
residuals = residuals(arma)
sqresid = residuals^2
acf2(sqresid, main="ACF and PACF of Squared Residuals", 25)
```


```{r}
log_diff_NKE_garch1 = garchFit(~arma(2,0)+garch(1,0), data=NKE_log_diff, cond.dist='std')
summary(log_diff_NKE_garch1)

log_diff_NKE_garch2 = garchFit(~arma(2,0)+garch(1,1), data=NKE_log_diff, cond.dist='std')
summary(log_diff_NKE_garch2)

log_diff_NKE_garch3 = garchFit(~arma(2,0)+garch(2,1), data=NKE_log_diff, cond.dist='std')
summary(log_diff_NKE_garch3)

log_diff_NKE_garch4 = garchFit(~arma(2,0)+garch(1,2), data=NKE_log_diff, cond.dist='std')
summary(log_diff_NKE_garch4)

log_diff_NKE_garch5 = garchFit(~arma(2,0)+garch(2,2), data=NKE_log_diff, cond.dist='std')
summary(log_diff_NKE_garch5)

log_diff_NKE_garch6 = garchFit(~arma(2,0)+garch(2,0), data=NKE_log_diff, cond.dist='std')
summary(log_diff_NKE_garch6)

aic_garch1 = NKE_garch1@fit$ics["AIC"]
aic_garch2 = NKE_garch2@fit$ics["AIC"]
aic_garch3 = NKE_garch3@fit$ics["AIC"]
aic_garch4 = NKE_garch4@fit$ics["AIC"]
aic_garch5 = NKE_garch5@fit$ics["AIC"]
aic_garch6 = NKE_garch6@fit$ics["AIC"]

aic_values = c(aic_garch1, aic_garch2, aic_garch3, aic_garch4, aic_garch5, aic_garch6)
model_names = c("GARCH(1,0)", "GARCH(1,1)", "GARCH(2,1)", "GARCH(1,2)", "GARCH(2,2)", "GARCH(2,0)")

aic_df = data.frame(Model = model_names, AIC = aic_values)

best_model = aic_df[which.min(aic_df$AIC),]

best_model
```

```{r}
par(mfrow=c(1,2))
plot(log_diff_NKE_garch1, which=c(1, 3, 9, 10))
plot(NKE_garch1, which=13)
```


```{r, warning=F}
log_diff_fcastGarch = predict(log_diff_NKE_garch1, n.ahead=252, nx=252, plot=TRUE)
summary(log_diff_fcastGarch)
```

```{r}
mean_forecast <- log_diff_fcastGarch$meanForecast
lower_forecast <- log_diff_fcastGarch$lowerInterval
upper_forecast <- log_diff_fcastGarch$upperInterval

# Step 1: Reverse the log and differencing transformation for the mean forecast
last_value <- tail(NKE_ts, 1)

# Initialize the reconstructed values with the last known value
reconstructed_values <- numeric(length(mean_forecast))
reconstructed_values[1] <- last_value * exp(mean_forecast[1])

# Reconstruct the forecasted values by cumulative multiplication
for (i in 2:length(reconstructed_values)) {
  reconstructed_values[i] <- reconstructed_values[i-1] * exp(mean_forecast[i])
}

# Step 2: Reverse the log and differencing transformation for the confidence intervals
lower_reconstructed <- numeric(length(lower_forecast))
upper_reconstructed <- numeric(length(upper_forecast))
lower_reconstructed[1] <- last_value * exp(lower_forecast[1])
upper_reconstructed[1] <- last_value * exp(upper_forecast[1])

for (i in 2:length(lower_reconstructed)) {
  lower_reconstructed[i] <- lower_reconstructed[i-1] * exp(lower_forecast[i])
  upper_reconstructed[i] <- upper_reconstructed[i-1] * exp(upper_forecast[i])
}

# Combine the reconstructed values with the original data
combined_series <- c(NKE_ts, reconstructed_values)

# Plot the original data and the forecasted data
plot.ts(combined_series, main="Original and Forecasted Series with Confidence Intervals", ylab="Value", xlab="Time")
lines(seq(length(NKE_ts) + 1, length(combined_series)), reconstructed_values, col="red")
lines(seq(length(NKE_ts) + 1, length(combined_series)), lower_reconstructed, col="blue", lty=2)
lines(seq(length(NKE_ts) + 1, length(combined_series)), upper_reconstructed, col="blue", lty=2)

# Adding a legend
legend("topright", legend=c("Original Data", "Forecasted Data", "95% Confidence Interval"), col=c("black", "red", "blue"), lty=c(1, 1, 2))
```

